USE University;

/* Time_Slot */
LOAD DATA LOCAL INFILE 'Time_Slot.csv'
INTO TABLE Time_Slot
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* SELECT COUNT(*) AS Time_Slots FROM; */

/* Classroom */
LOAD DATA LOCAL INFILE 'Classroom.csv'
INTO TABLE Classroom
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* SELECT COUNT(*) AS Classrooms FROM; */

/* Department */
LOAD DATA LOCAL INFILE 'Department.csv'
INTO TABLE Department
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* SELECT COUNT(*) AS Departments FROM; */

/* Instructor */
LOAD DATA LOCAL INFILE 'Instructor.csv'
INTO TABLE Instructor
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* SELECT COUNT(*) AS Instructors FROM; */

/* Student */
LOAD DATA LOCAL INFILE 'Student.csv'
INTO TABLE Student
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* SELECT COUNT(*) AS Students FROM; */

/* Advisor */
LOAD DATA LOCAL INFILE 'Advisor.csv'
INTO TABLE Advisor
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* SELECT COUNT(*) AS Advisors FROM; */

/* Course */
LOAD DATA LOCAL INFILE 'Course.csv'
INTO TABLE Course
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* SELECT COUNT(*) AS Courses FROM; */

/* Prereq */
LOAD DATA LOCAL INFILE 'Prereq.csv'
INTO TABLE Prereq
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* SELECT COUNT(*) AS Prereqs FROM; */

/* Section */
LOAD DATA LOCAL INFILE 'Section.csv'
INTO TABLE Section
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* SELECT COUNT(*) AS Sections FROM; */

/* Teaches */
LOAD DATA LOCAL INFILE 'Teaches.csv'
INTO TABLE Teaches
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* SELECT COUNT(*) AS Teaches FROM; */

/* Takes */
LOAD DATA LOCAL INFILE 'Takes.csv'
INTO TABLE Takes
COLUMNS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* SELECT COUNT(*) AS Takes FROM; */