class Course:
    count = 0

    def __init__(self, course_id, name, department_name, credits):
        self.ID = course_id
        self.name = name
        self.department_name = department_name
        self.credits = credits
        Course.count += 1

    def headers(self):
        return 'ID,name,department_name,credits\n'
    
    def printLine(self):
        return '{0},{1},{2},{3}\n'.format(self.ID, self.name, self.department_name, self.credits)


course_catalog = {
    'CSE': [
        'Fundamentals of Software Development 1',
        'Fundamentals of Software Development 2',
        'Ideas and Impact of Computing',
        'Computing Disciplines and Careers 1',
        'Introduction to Computer Applications',
        'Introduction to Software Development With C++',
        'Introduction to Software Development With FORTRAN',
        'Algorithms and Data Structures',
        'Programming In a Second Language',
        'Computer Organization and Machine Programming',
        'Introduction to System Administration',
        'Applied Statistics',
        'Introduction to Software Engineering',
        'Legal, Ethical, and Social Issues In Computing',
        'Computer Architecture and Assembly Programming',
        'Operating Systems Concepts',
        'Advanced Java Concepts',
        'Introduction to Analysis of Algorithms',
        'Introduction to Parallel and Real-Time Algorithms',
        'Computer Science Projects 1',
        'Computer Science Projects 2',
        'Software Development Projects 1',
        'Software Development Projects 2',
        'Computer Network Programming',
        'Programming Language Concepts',
        'Compiler Theory',
        'Computer Graphics Algorithms',
        'Game Design',
        'Introduction to Artificial Intelligence',
        'Speech Recognition Programming',
        'Software Project Management',
        'Special Topics In Computer Science',
        'Formal Languages and Automata Theory',
        'Analysis of Algorithms',
        'Computer Networks',
        'Network Programming',
        'Computer Forensics',
        'Web Applications',
        'Parallel Processing',
        'Distributed Computing',
        'Programming Languages',
        'Compiler Theory and Design',
        'Database Systems',
        'Computer and Information Security',
        'Computer Graphics',
        'Graphical User Interfaces',
        'Computer Vision',
        'Artificial Intelligence',
        'Topics In Computer Science',
        'Independent Study In Computer Science',
        'Projects In Computer Science',
        'Computer Science Seminar',
        'Computer Sciences Internship',
        'Computational Complexity',
        'Computational Molecular Biology',
        'Advanced Operating Systems',
        'Network Security',
        'Advanced Programming Languages',
        'Theory and Applications of Complex Networks',
        'Database Management Systems',
        'Software Design Methods',
        'Introduction to Malicious Mobile Code',
        'Cryptology',
        'Advanced Computer Vision',
        'Constraint Reasoning',
        'Machine Learning',
        'Robotics and Artificial Intelligence',
        'Pattern Recognition In Biomedical Applications',
        'Advanced Topics In Computer Science',
        'Independent Research In Computer Science',
        'Research Projects In Computer Science',
        'Advanced Topics In Computer Science Theory',
        'Advanced Topics In Computer Networks',
        'Advanced Topics In Database Systems',
        'Final Semester Thesis In CSE',
        'Thesis In CSE',
        'Final Semester Dissertation In CSE',
        'Research In Computer Science',
        'Dissertation In CSE'
    ], 
    'MTH': [
        'Basic Algebra',
        'Intermediate Algebra',
        'Precalculus',
        'Calculus 1',
        'Calculus 2',
        'Precalculus A',
        'Precalculus B',
        'Introductory Discrete Mathematics',
        'Applied Calculus and Statistics',
        'College Algebra',
        'Applied Calculus',
        'Finite Mathematics',
        'Trigonometry Review',
        'Calculus 3',
        'Discrete Mathematics',
        'Differential Equations/Linear Algebra',
        'Linear Algebra for Differential Equations',
        'Probability and Statistics',
        'Functions and Modeling',
        'Combinatorics and Graph Theory',
        'Complex Variables',
        'Introduction to Linear Algebra',
        'Introduction to Partial Differential Equations and Applications',
        'Finite Differences and Finite Elements',
        'Introduction to Number Theory',
        'Mathematical Methods for Biology and Ecology',
        'Selected Topics on Biostochastics',
        'Abstract Algebra',
        'Introduction to Parallel Processing',
        'Introductory Analysis In MTH',
        'Topology',
        'Models In Applied Mathematics',
        'Stochastic Modeling',
        'Numerical Analysis ',
        'Neural Networks',
        'Advanced Geometry',
        'Special Topics In Applied Mathematics',
        'Undergraduate Research',
        'Introduction to Optimization',
        'Introduction to Probabilistic Models',
        'Special Topics',
        'Applied Discrete Mathematics',
        'Educational Statistics',
        'Introductory Analysis',
        'Linear Algebra',
        'Optimization Models and Methods',
        'Real Variables 1',
        'Functional Analysis',
        'Applied Complex Variables',
        'Theory of Complex Variables',
        'Mathematical Methods In Science and Engineering 1',
        'Mathematical Methods In Science and Engineering 2',
        'Mathematical Methods In Science and Engineering 3',
        'Theory of Ordinary Differential Equations',
        'Partial Differential Equations',
        'Numerical Analysis',
        'Numerical Methods for Ordinary Differential Equations',
        'Numerical Methods for Partial Differential Equations',
        'Applied Statistical Analysis',
        'Mathematical Statistics 1',
        'Mathematical Statistics 2',
        'Theory of Stochastic Processes',
        'Theory of Stochastic Signals',
        'Queuing Theory',
        'Stochastic Analysis of Financial Markets 1',
        'Stochastic Analysis of Financial Markets 2',
        'Final Semester Thesis In MTH',
        'Thesis In MTH',
        'Research In Applied Mathematics',
        'Selected Topics In Nonlinear Analysis',
        'Partial Differential Equations 2',
        'Selected Topics In Numerical and Computational Mathematics',
        'Calculus of Variation and Optimal Control',
        'Final Semester Dissertation In MTH',
        'Dissertation Research'
    ],
    'CHM': [
        'Nanoscience/Nanotechnology Laboratory',
        'Introduction to Chemistry',
        'General Chemistry 1',
        'General Chemistry 2',
        'Organic Chemistry 1',
        'Organic Chemistry 2',
        'Organic Chemistry Laboratory 1',
        'Organic Chemistry Laboratory 2',
        'Physical Chemistry 1',
        'Physical Chemistry 2',
        'Physical Chemistry Laboratory 1',
        'Physical Chemistry Laboratory 2',
        'Analytical Chemistry 1',
        'Analytical Chemistry 2: Instrumentation',
        'Analytical Chemistry Laboratory 1',
        'Analytical Chemistry 2: Instrumentation Laboratory',
        'Inorganic Chemistry 1',
        'Environmental Chemistry',
        'Advanced Laboratory Techniques 1',
        'Physical Biochemistry',
        'Undergraduate Research In CHM 1',
        'Undergraduate Research In CHM 2',
        'Chemistry Seminar',
        'Senior Research Seminar',
        'Senior Thesis In Chemistry 1',
        'Senior Thesis In Chemistry 2',
        'Advanced Inorganic Chemistry',
        'Physical Methods In inorganic Chemistry',
        'Special Topics In inorganic Chemistry',
        'Chemical Research Projects',
        'Advanced Physical Chemistry',
        'Special Topics In Physical Chemistry',
        'Applied Optical Spectroscopy',
        'Chemical Dynamics',
        'Green Chemistry',
        'Advanced Analytical Chemistry',
        'Special Topics In Analytical Chemistry',
        'Advanced Organic Chemistry',
        'Interpretation of Chemical Spectra',
        'Organic Synthesis',
        'Theoretical Organic Chemistry',
        'Natural Products',
        'Bioorganic Chemistry',
        'Medicinal Chemistry',
        'Polymer Chemistry',
        'Final Semester Thesis In CHM',
        'Chemistry Graduate Seminar',
        'Chemistry Thesis Seminar',
        'Thesis',
        'Chemical Research',
        'Final Semester Dissertation',
        'Dissertation In CHM'
    ],
    'BIO': [
        'Biological Discovery 1',
        'Biological Discovery 2',
        'Introduction to the Health Professions',
        'Introduction to Aquaculture',
        'Microbiology',
        'General Genetics',
        'Primer for Biomath',
        'Biometry',
        'Field Biology and Ecology Africa',
        'Field Biology and Ecology Smoky Mountains',
        'Field Biology and Ecology Coral Reefs',
        'Anatomy and Physiology 1',
        'Anatomy and Physiology 2',
        'Mammalian Physiology',
        'Developmental Biology',
        'General Ecology',
        'Invertebrate Zoology',
        'Field Methods In Fisheries Science',
        'Molluscan Aquaculture',
        'Evolution',
        'Ecology of Tropical Ecosystems',
        'Tropical Marine Ecology',
        'Biochemistry 1',
        'Methods In Protein Analysis',
        'Special Topics In Biology',
        'Molecular Biology',
        'Biochemistry 2',
        'Genetic Engineering Techniques',
        'Nucleic Acid Analysis',
        'Special Topics In Molecular Biology',
        'Immunology',
        'Molecular Biology of Plants',
        'Plant Physiology',
        'Cell Biology',
        'Molecular Basis of Human Disease',
        'Community Ecology',
        'Ecology of Coral Reefs',
        'Introduction to Modeling for Ecology and Biology',
        'Biology of Fishes',
        'Comparative Vertebrate Anatomy',
        'Fish Aquaculture and Management',
        'Crustacean Aquaculture',
        'Biology of Marine Mammals',
        'Marine Biology',
        'Marine Ecology',
        'Field Biology and Evolution of the Galapagos Islands',
        'Biology Forum',
        'Undergraduate Research 1',
        'Undergraduate Research 2',
        'Undergraduate Research 3',
        'Comparative Biology of Invertebrates',
        'Ichthyology',
        'Ornithology',
        'Protein Biotechnology',
        'Plant Biotechnology',
        'Laboratory Methods for Biotechnology',
        'Field Ecology 1',
        'Coral Reef Ecology',
        'Field Ecology 4',
        'Ecology of Salt Marsh and Mangrove',
        'Design and Analysis of Ecological Studies',
        'Chemical Ecology',
        'Conservation Biology',
        'Conservation Genetics',
        'Paleoclimatology and Paleoecology',
        'Plant Systematics and Biogeography',
        'Marine Mammalogy',
        'Reproduction and Recruitment of Marine Fishes',
        'Ecological Physiology of Fishes',
        'Biology and Ecology of Seagrasses',
        'Natural History of the Indian River Lagoon',
        'Physiological Ecology',
        'Multivariate Analysis In Biology',
        'Mechanisms of Biological Clocks',
        'Biological Imaging',
        'Ecology of Tropical Communities',
        'Coral Ecology',
        'Landscape Ecology',
        'Applied Physiology',
        'Applied Geographic Information Systems for Biological Research',
        'Pre-Columbian Ecosystems',
        'Neotropical Archeoecology',
        'Cell and Molecular Biology',
        'Molecular Biology of Signal Transduction',
        'Current Topics In Ecology',
        'Topics In Evolution',
        'Pharmacology and Drug Design',
        'Modeling for Ecology and Biology',
        'Bioinformatics, Genomics and Proteomics',
        'Biology of Aging',
        'Applied Biotechnology',
        'Microbial Biotechnology',
        'Growth and Division of Cells 1: Prokaryotes',
        'Genomic Instability and Human Disease',
        'Scientific Analysis, Writing and Presentation',
        'Biology of Cancer',
        'Molecular Genetics',
        'Protein Structure and Function',
        'Sensory Biology',
        'Introductory Neurobiology',
        'Final Semester Thesis',
        'Biological Sciences Seminar',
        'Biological Research Seminar',
        'Biological Research',
        'Industrial Internship',
        'Biological Research Rotation',
        'Thesis In BIO',
        'Final Semester Dissertation In BIO',
        'Dissertation In BIO'
    ],
    'HUM': [
        'Popular Culture for Freshmen',
        'Humanities Freshman Seminar',
        'Creative Arts Practicum',
        'Fundamentals of Color 1',
        'Fundamentals of Color 2',
        'Mythology',
        'Art Appreciation',
        'Integrated Arts',
        'Philosophy of Human Nature',
        'Religions of the World 1: Western Religions',
        'Religions of the World 2: Eastern Religions',
        'Ethics',
        'Civilization 1: Ancient Through Medieval',
        'Civilization 2: Renaissance Through Modern',
        'Critical Approaches to Humanities and Social Sciences',
        'World Architecture',
        'World Art History 1: Pre-History to Early Global Awareness',
        'World Art History 2: Early Modern to Post-Colonial',
        'Popular Music and Culture',
        'British and American Literature',
        'British and American Literature 2',
        'Survey of World Literature 2',
        'Literature: Voice and Vision',
        'American History: Pre-Columbian to Civil War Era',
        'American History: From Reconstruction to the Present',
        'Special Topics In World History',
        'Introduction to Law',
        'Introduction to Political Science',
        'Logic',
        'Bioethics',
        'History and Culture of China',
        'Special Topics In Humanities',
        'Masterworks of Music',
        'Special Topics In Fine Arts',
        'Literary Theory',
        'Shakespeare and His Contemporaries',
        'Contemporary Literature',
        'Science Fiction Literature and Film',
        'Young Adult Literature',
        'Crime In Fiction',
        'Monsters In Fiction',
        'Narrative Film',
        'Television and Popular Culture',
        'Special Topics In Literature',
        'American Military History',
        'World War II History In Film',
        'History of Science and Technology: Ancient and Medieval',
        'History of Science and Technology: Renaissance to Present',
        'Special Topics In History',
        'Constitutional Law 1',
        'Constitutional Law 2',
        'Special Topics In Social Science',
        'World Religions',
        'Survey of Ancient and Medieval Philosophy',
        'Survey of Modern and Contemporary Philosophy',
        'Special Topics In Philosophy',
        'Introduction to the Humanities',
        'Junior Seminar In the Humanities',
        'Capstone Research Methods',
        'Senior Capstone Project',
        'Independent Study',
        'Recent Issues In Logic'
    ],
    'ECE': [
        'Digital Logic',
        'Computer Design',
        'Undergraduate Research In Electrical or Computer Engineering',
        'Circuit Theory 1',
        'Circuit Theory 2',
        'Software/Hardware Design',
        'Software/Hardware Integration',
        'Electronics',
        'Signals and Systems',
        'Junior Design',
        'Electron Devices',
        'Electromagnetic Fields',
        'Electromagnetic Waves',
        'Digital State Machines',
        'Microcomputer Systems 1',
        'Microcomputer Systems 2',
        'Multifarious Systems 1',
        'Digital Electronics',
        'Electronics Design',
        'Communication Systems',
        'Communications and Control Systems Laboratory',
        'Pattern Recognition and Detection',
        'Control Systems',
        'System Design 1',
        'System Design 2',
        'Special Topics In Electrical and Computer Engineering',
        'Microelectronics Fabrication Laboratory',
        'Electrooptic Devices and Systems',
        'Lightwave Laboratory',
        'Virtual Instrumentation Lab',
        'Computer Architecture',
        'Computer Communications',
        'Introduction to Electrical Power Systems',
        'Independent Study In ECE',
        'Electric and Electronic Circuits',
        'Radio Frequency Propagation',
        'Wireless Local Area Networks',
        'Modern Wireless Design Concepts',
        'Multimedia Communications',
        'Wireless Sensor Networks',
        'Wireless Communications',
        'Advanced Topics In Wireless Communication',
        'Linear Systems 1',
        'Linear Systems 2',
        'Personal Communication Systems',
        'Digital Communications',
        'Satellite Communications',
        'Communications Theory',
        'Error Control Coding',
        'Digital Control Systems',
        'Digital Signal Processing 1',
        'Digital Signal Processing 2',
        'Advanced Filtering',
        'Radar Systems',
        'Digital Image Processing',
        'Pattern Recognition',
        'Medical Imaging',
        'Theory and Applications of Neural Networks',
        'Special Topics In Systems',
        'Model-Based Systems Engineering',
        'CubeSat Design',
        'Semiconductor Device Theory',
        'VLSI Processing',
        'Microelectronics Fabrication Lab',
        'IC Computer-Aided Analysis',
        'Analog IC Design',
        'Optical Electronics',
        'Fiber-Optic Communication Systems',
        'Fiber-Optic Sensor Systems',
        'Acoustooptic and Electrooptic Devices',
        'Electrooptics Laboratory',
        'Optical Waveguides and Devices',
        'Special Topics In Photonics',
        'Special Topics In Microelectronics',
        'Electrodynamics 1',
        'Field Theory of Guided Waves 1',
        'Field Theory of Guided Waves 2',
        'Antennas 1',
        'Antennas 2',
        'Computational Electromagnetics',
        'Special Topics In Electromagnetics',
        'Special Project In Electrical Engineering',
        'Computer Architecture In ECE',
        'Speech Processing',
        'Speech Recognition',
        'Search and Decoding In Speech Recognition',
        'Acoustics of American English Speech',
        'Audio Processing In Wireless Communications',
        'Computer Networks 1',
        'Computer Networks 2',
        'Cloud Computing',
        'High-Performance Computing',
        'Wavelet Transforms for Image Processing',
        'Computer Systems',
        'Embedded and Real-Time Systems',
        'Special Topics In Computer Engineering',
        'Programmable Gate Arrays',
        'Android Embedded Application Development',
        'Special Projects In Computer Engineering',
        'Power Systems Operation and Control',
        'Power System Reliability and Planning',
        'Final Semester Thesis In ECE',
        'Internship In Electrical and Computer Engineering',
        'Thesis In Electrical or Computer Engineering',
        'Final Semester Dissertation In ECE',
        'Research and Dissertation In Electrical or Computer Engineering'
    ],
    'SWE': [
        'Software Engineering 1',
    'Software Engineering 2',
    'Requirements Engineering',
    'Windows Systems Programming',
    'Software Testing 1',
    'Software Testing 2',
    'Software Testing Tools',
    'Introduction to Software Architecture',
    'Software Maintenance',
    'Software Metrics and Modeling',
    'Secure Software Development',
    'Final Semester Thesis In SWE',
    'Special Topics In Software Engineering',
    'Thesis In SWE'
    ],
    'PSY': [
        'PHY  Leadership Seminar',
        'Psychology Seminar',
        'Introduction to Psychology',
        'Psychology of Adjustment and Personal Growth',
        'Substance Abuse',
        'Human Sexuality',
        'Life Span Development and Psychology',
        'Research Experience',
        'Adult Development and Aging',
        'Cross-Cultural and Ethnic Psychology',
        'Psychology of Women',
        'Sport Psychology',
        'Research and Computer Literacy',
        'Psychology Research Methods and Statistics 1',
        'Group Behavior',
        'Introduction to Behavior Analysis',
        'Research Methods In Applied Psychology',
        'Applied Psychology',
        'Law and Psychology',
        'Psychology of Disasters',
        'Multicultural Issues',
        'Special Topics In Psychology',
        'Psychology of Learning and Motivation',
        'Physiological Psychology',
        'Health Psychology',
        'Social Psychology',
        'Psychology of Personality',
        'Psychological Research Methods and Statistics 2',
        'Memory',
        'Human Cognition: Theory and Application',
        'Sensation and Perception',
        'Child Psychology',
        'Psychology of Leadership',
        'Psychology of the Workplace',
        'Introduction to Child Advocacy',
        'Abnormal Psychology',
        'Experimental Psychology 1',
        'Scholarly Project Planning Seminar',
        'Field Internship and Research Project',
        'Applied Research Analysis Seminar',
        'Applied Tests and Measures',
        'Organizational Psychology and Behavior',
        'Undergraduate Research In PSY',
        'Clinical and Community Psychology',
        'Principles of Program Development and Evaluation',
        'Personal and Professional Development',
        'Psychology Honors Thesis',
        'Animal Learning and Behavior',
        'Comparative Animal Cognition',
        'Culture and Psychology',
        'Psychology Honors Seminar',
        'Employment and Personality Testing',
        'Professional and Ethical Issues',
        'Clinical Colloquium',
        'Pre-Practicum',
        'Hypnotherapy',
        'Introduction to Research In I/O Psychology',
        'Statistical Research Methods 1',
        'Statistical Research Methods 2',
        'Biological Foundations of Behavior',
        'Life-Span Development',
        'Program Evaluation',
        'Substance Abuse: Research and Treatment',
        'History and Systems of Psychology',
        'Cognitive and Affective Bases of Behavior',
        'Foundations of Leadership',
        'Organizational Science: Theory and Application',
        'Analytics and Research In Organizational Science',
        'Cultural and Social Psychology',
        'Cross-Cultural Theory and Research Methods',
        'Leading Diverse Teams',
        'Organizational Consulting Skills',
        'Directed Readings In Psychology',
        'Seminar In Psychology',
        'Seminar In Play Therapy',
        'Supervised Research',
        'Ethics In Leadership and Corporate Social Responsibility',
        'Talent Management',
        'Leadership In a Global Context',
        'Negotiation and Conflict Management',
        'High Impact Communication',
        'Contemporary Leadership',
        'Research In Leadership',
        'Introduction to Industrial and Organizational Psychology',
        'Tests and Measurements',
        'Applied Research Methods',
        'Personnel Selection',
        'Performance Appraisal',
        'Personnel Law',
        'Organizational Psychology',
        'Organizational Change and Transformation',
        'Industrial Training',
        'Group and Team Development',
        'Emotions In the Workplace',
        'Work Motivation',
        'Occupational Health Psychology',
        'Leadership Seminar',
        'Current Topics In industrial and Organizational Psychology',
        'Practicum In industrial and Organizational Psychology',
        'Organizational Change and Change Leadership',
        'Organizational Leadership: Strategy and Execution',
        'Personality and Psychotherapy',
        'Psychopathology',
        'Clinical Psychopharmacology',
        'Assessment of Intelligence',
        'Laboratory In Assessment of Intelligence',
        'Laboratory In Assessment of Personality',
        'Objective Personality Assessment',
        'Projective Personality Assessment',
        'Assessment of Childhood Developmental Disorders',
        'Parent-Child Interaction Therapy',
        'Clinical Skills and Techniques 1',
        'Clinical Skills and Techniques 2',
        'Clinical Hypnosis',
        'Dynamics of Group Psychotherapy',
        'Psychotherapy Models: Cognitive Behavioral',
        'Psychotherapy Models: Psychodynamic',
        'Psychotherapy Models: Humanistic/Existential',
        'Psychotherapy Models: Family Approaches',
        'Child Disorders and Psychotherapy',
        'Multicultural Psychotherapy',
        'Seminar In Professional Standards and Ethical Principles In Psychology 1',
        'Seminar In Professional Standards and Ethical Principles In Psychology 3',
        'Practicum',
        'Supervised Clinical Experience',
        'Final Semester Thesis In PSY',
        'Seminar In Professional Standards and Ethical Principles In Psychology 2',
        'Thesis In PSY',
        'Forensic Psychology',
        'Introduction to Forensic Psychology',
        'Fundamentals of Forensic Psychology',
        'Clinical Forensic Assessment',
        'Supervised Research In PSY',
        'Independent Research In industrial and Organizational Psychology',
        'Chaos Theory In Organizations',
        'Multivariate Statistics',
        'Cultural Seminar In industrial and Organizational Psychology',
        'Cultural Research Applications In industrial and Organizational Psychology',
        'Global Leadership',
        'Global Talent Management',
        'International Change Management',
        'Hierarchical Linear Modeling',
        'Attitudes and Values In industrial and Organizational Psychology',
        'Advanced Research Seminar In industrial and Organizational Psychology',
        'Current Topics In international Industrial and Organizational Psychology',
        'Psychodiagnostics',
        'Neuropsychology and Neuropsychological Assessment',
        'Fundamentals of Clinical Neuropsychology',
        'Death and Dying',
        'Post-Traumatic Stress Disorder',
        'Marital and Sex Therapy',
        'Supervision In Clinical Training',
        'Consultation',
        'Administration of Mental Health Services',
        'Clinical Applications In Behavioral Healthcare',
        'Behavioral Medicine Case Conference',
        'Supervision and Consultation',
        'Clinical Internship Preparation Lab',
        'Internship',
        'Final Semester Doctoral Research Project',
        'Final Semester Dissertation In PSY',
        'Doctoral Research Project',
        'Dissertation In PSY'
    ]}